volumes:
  postgres:

services:
  postgres:
    container_name: postgres
    build:
      context: database
      dockerfile: Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          memory: 500M
    volumes:
      - postgres:/var/lib/pgsql/data

  douyin_api:
    container_name: douyin_api
    build:
      context: douyin_api
      dockerfile: Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          memory: 500M
    environment:
      TZ: Asia/Shanghai
      PUID: 1026
      PGID: 100
    privileged: true

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
      # 使用 nvidia gpu 请注释掉上面一行使用下面这行
      # dockerfile: Dockerfile.cuda
    volumes:
      - ./backend:/app
    command: python3 /app/run.py
    restart: always
    deploy:
      resources:
        limits:
          memory: 5000M
        # 使用 nvidia gpu 请添加下面的配置
        # reservations:
        #   devices:
        #     - driver: nvidia
        #       count: 1
        #       capabilities: [gpu]

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5173:5173
