FROM modelscope-registry.cn-hangzhou.cr.aliyuncs.com/modelscope-repo/modelscope:ubuntu22.04-cuda12.1.0-py310-torch2.3.1-tf2.16.1-1.22.2

RUN pip install Flask Flask-SQLAlchemy Flask-Cors requests psycopg2-binary
